name: Sharedhosting deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar entorno PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4.16"

      # - name: Install dependencies
      #   run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest
      # - name: Configure env
      #  env:
      #   FTP_HOST: ${{ secrets.FTP_HOST }}
      #  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      # FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      #FTP_DESTINATION: ${{ secrets.FTP_DESTINATION }}
      #run: php artisan config:cache
      # - name: Deploy to shared hosting

      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.5.3 # Configura el agente SSH
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }} # Usa tu secreto SSH

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          script: |
            cd /var/www/Calculadora-Crypto
            git pull origin master
