name: Sharedhosting deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar entorno PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4.16"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # 1. Ir a la carpeta del proyecto
            cd /var/www/Calculadora-Crypto

            # 2. Poner la aplicación en modo mantenimiento (opcional pero recomendado)
            php artisan down || true

            # 3. Traer los últimos cambios
            git pull origin master

            # 6. Limpiar y cachear configuraciones
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # 7. Compilar assets de Frontend (Si usas Vite/Mix)
            npm install
            npm run build

            # 8. Ajustar permisos (Crucial para Apache)
            # Asegúrate que el usuario web (www-data) tenga acceso a storage y cache
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # 9. Reiniciar colas (si usas Laravel Horizon o Supervisor)
            php artisan queue:restart

            # 10. Levantar la aplicación
            php artisan up
